### ISSUE TITLE
v1.4.2 causes error undefined reference to `fstat64'

### ISSUE THREAD

**Issue by Eetami** [graalvm/setup-graalvm#190]
When building a Quarkus native application using musl toolchain from graalvm, builds fail on above error.
Builds work fine with v1.4.1.

**Comment by fniephaus** [comment]
Thanks for filing the ticket, @Eetami. We have fixed the error you mentioned some time ago, so either you are using an old version of Mandrel or the bug fix has not been backported. What version of Mandrel are you using? Could you share a link to the failing build?

The problem is that the musl toolchain previously used is old and is affected by CVEs (see https://musl.libc.org). Reverting to this musl toolchain is therefore not a good idea. Alternatively, you could use Oracle GraalVM 25 instead of Mandrel until this is fixed in Mandrel.

@zakkak, this is the corresponding fix: https://github.com/oracle/graal/pull/9073
